"""Generate the Appendix B parameter register from the code's own declarations.

Writes thesis/chapters/appendix_b_register.tex from simulation.config.parameter_register(),
so the appendix, the ParamSet defaults and the sweep annotations cannot drift apart.
Re-run after any change to simulation/config.py:

    ./env/python.exe notebooks/scripts/generate_param_register.py
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))

from simulation.config import parameter_register  # noqa: E402

OUT = ROOT / "thesis" / "chapters" / "appendix_b_register.tex"

#: Sentences of `source` metadata carried into the table. The full text lives in
#: config.py; the register needs the identifying claim, not the working history.
MAX_SENTENCES = 3
MIN_CHARS = 60

ARROW = "\x00ARROW\x00"

LATEX_SPECIALS = {
    "&": r"\&",
    "%": r"\%",
    "#": r"\#",
    "_": r"\_",
    "~": r"\textasciitilde{}",
    "^": r"\textasciicircum{}",
    "<": r"\textless{}",
    ">": r"\textgreater{}",
    "$": r"\$",
}


def escape(text: str) -> str:
    text = text.replace("->", ARROW)
    text = "".join(LATEX_SPECIALS.get(c, c) for c in text)
    return text.replace(ARROW, r"$\to$")


def escape_param(name: str) -> str:
    """Parameter names are typewriter and unbreakable; allow breaks at underscores."""
    return name.replace("_", r"\_\allowbreak{}")


def shorten(source: str) -> str:
    sentences = re.split(r"(?<=[.!?])\s+", source.strip())
    kept: list[str] = []
    for s in sentences:
        kept.append(s)
        if len(kept) >= MAX_SENTENCES:
            break
        if sum(len(k) for k in kept) >= MIN_CHARS:
            break
    return " ".join(kept)


def fmt_baseline(value: str) -> str:
    return escape(value)


PROVENANCE_LABELS = {"SOURCED": "sourced", "DERIVED": "derived", "ASSUMPTION": "assumed"}

RULE_LABELS = {"OVERVIEW 1a": "O.1a"}


def fmt_rule(rule: str) -> str:
    rule = RULE_LABELS.get(rule, rule)
    return escape(rule).replace("/", r"/\allowbreak{}")


def main() -> None:
    rows = parameter_register()
    lines = [
        "% GENERATED by notebooks/scripts/generate_param_register.py from",
        "% simulation/config.py -- do not edit by hand; re-run the script instead.",
        r"\begingroup",
        r"\setlength{\tabcolsep}{3pt}",
        r"\newcolumntype{R}[1]{>{\scriptsize\raggedright\arraybackslash}p{#1}}",
        r"\begin{longtable}{R{2.5cm}R{1.1cm}R{1.75cm}R{1.1cm}R{3.8cm}R{2.9cm}}",
        r"\caption{The full parameter register, generated from the model's parameter",
        r"declarations. Provenance: sourced = a citation fixes the value; derived = the",
        r"value is computed from data, not chosen; assumed = no anchor exists and",
        r"sensitivity analysis is mandatory.}",
        r"\label{tab:param-register} \\",
        r"\toprule",
        r"\textbf{Parameter} & \textbf{Rule} & \textbf{Baseline} & \textbf{Prov.} & \textbf{Source} & \textbf{Sweep} \\",
        r"\midrule",
        r"\endfirsthead",
        r"\toprule",
        r"\textbf{Parameter} & \textbf{Rule} & \textbf{Baseline} & \textbf{Prov.} & \textbf{Source} & \textbf{Sweep} \\",
        r"\midrule",
        r"\endhead",
        r"\bottomrule",
        r"\endfoot",
    ]
    for row in rows:
        cells = [
            r"\texttt{" + escape_param(row["parameter"]) + "}",
            fmt_rule(row["rule"]),
            fmt_baseline(row["baseline"]),
            PROVENANCE_LABELS.get(row["provenance"], escape(row["provenance"])),
            escape(shorten(row["source"])),
            escape(row["sweep"]) if row["sweep"] else "--",
        ]
        lines.append(" & ".join(cells) + r" \\")
        lines.append(r"\addlinespace")
    if lines[-1] == r"\addlinespace":
        lines.pop()
    lines += [r"\end{longtable}", r"\endgroup", ""]

    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)} ({len(rows)} parameters)")


if __name__ == "__main__":
    main()
